version: '2.0'

services:
  front:
    build:
      context: .
    volumes:
      - .:/vistop
      - node_modules:/vistop/node_modules
    command: bash -c "chmod -R 777 /vistop/node_modules/ && npm start"
    environment:
      - REACT_APP_SERVER_URL=http://localhost/api
    ports:
      - "3000:3000"
    privileged: true
    networks:
      - vistop
volumes:
  node_modules:
networks:
  vistop:
